export const FIND_PRODUCT_BY_ID_REGUEST = "FIND_PRODUCT_BY_ID_REGUEST";
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCT_BY_ID_SUCCESS";
export const FIND_PRODUCT_BY_ID_FAILURE = "FIND_PRODUCT_BY_ID_FAILURE";
